### ISSUE TITLE
Minimum number of Invoice documents required

### ISSUE THREAD

**Issue by hitesh1997** [naiveHobo/InvoiceNet#17]
What is the minimum count of Invoice documents required to get a decent generalized model?

**Comment by naiveHobo** [comment]
This is really a question with no good answer. I've seen decent performance for some general fields like total amount and invoice number with as little as 100 samples. But there's no guarantee that a model trained for these fields on a small dataset would be able to generalize well. Other, slightly more complex fields like invoice date take a lot more samples to produce decent results.
