### ISSUE TITLE
dataset and pickle file not available

### ISSUE THREAD

**Issue by snehasahu26** [naiveHobo/InvoiceNet#2]
hello can you please provide the dataset and pickle file . please

**Comment by bhaskar2500** [comment]
Hi Sarthak ,

It will be very helpful if you provide dataset for this example . I am unable to test/run this script .

Thanks ,
Bhaskar

**Comment by edkbbe** [comment]
Yes can you please add the dataset.

Thanks
Ed K.

**Comment by chrike-platinum** [comment]
I would also like this.
Thanks!

**Comment by nitml** [comment]
can you upload some dataset

**Comment by mon28** [comment]
Yes, please provide sample dataset and pickle file.

**Comment by divz1010** [comment]
yes please provide sample dataset and pickle file.

**Comment by divz1010** [comment]
Hi Sarthak,

It will be very helpful if you provide a dataset for this example. I am unable to test/run this script.

**Comment by naiveHobo** [comment]
I added the data set file and some supporting files in the following commit: a931196
Closing this issue.
