### ISSUE TITLE
I'm facing issue near prepare_data.py.

### ISSUE THREAD

**Issue by nithinreddyy** [naiveHobo/InvoiceNet#24]
python prepare_data.py --data_dir train_data/ 

In the above what should i do like when should i place my directory? For example, my directory is C:\Users\NITHIN\invoicenet\InvoiceNet how should i write the code? 

Thanks

**Comment by naiveHobo** [comment]
Replace train_data/ with the absolute path to the directory that contains you training data. That should do it!
