### ISSUE TITLE
prepare_data.py  -   tesseract is not installed or it's not in your PATH. 

### ISSUE THREAD

**Issue by daoud** [naiveHobo/InvoiceNet#33]
I am working on prepare_data.py. please check the below command for running code. I had successfully created the image from the .pdf file that is saved in the processed_data folder (train, val).
### **ngrams = util.create_ngrams(page)**    from this line my code throwing exception. please check below.

**### Skipping C:\Users\Daoud\Documents\ComputerVision\InvoiceNet-master\train_data\9.pdf : tesseract is not installed or it's not in your PATH.** 

 I have installed tesseract already. 
**### "C:\Program Files (x86)\Tesseract-OCR"**   tesseract path in my system. 
In the prepare_data.py  file code there no line where we calling the tesseract method. I am a little confuse 

please give me the solution.
thank you in advanced

**Comment by naiveHobo** [comment]
> In the prepare_data.py file code there no line where we calling the tesseract method

InvoiceNet uses pytesseract (python bindings for tesseract OCR) to extract text from a document when data is prepared before training/inference.

> tesseract is not installed or it's not in your PATH.

As the error message suggests, tesseract is not installed correctly on your system. I'm sure if you try to run the [examples provided by pytesseract](https://pypi.org/project/pytesseract/), you'll get the same error. It's not an issue with InvoiceNet.

I have provided [install instructions for InvoiceNet for Windows 10](https://github.com/naiveHobo/InvoiceNet#windows-10) and links to install instructions for the different dependencies in the README. Try reinstalling tesseract on your system and testing the pytesseract examples to make sure tesseract is working correctly. Let me know if you face any further issues!
