### ISSUE TITLE
Issue with pattern encoder

### ISSUE THREAD

**Issue by HarpreetSethi1** [naiveHobo/InvoiceNet#36]
When I debug the code, I found the the pattern regex is not working fine for me. Its converting everything to '-'. 
Code under invoicenet/acp/data.py

pattern = text
pattern = re.sub(r"\\p{Lu}", "X", pattern)
pattern = re.sub(r"\\p{Ll}", "x", pattern)
pattern = re.sub(r"\\p{N}", "0", pattern)
pattern = re.sub(r"[^Xx0]", "-", pattern)

**Comment by naiveHobo** [comment]
Thank you for pointing this out! This was due to a python 2.7 to python 3.7 jump. Those regex used to work in python 2.7.
