### ISSUE TITLE
Dataset and supported files are missing

### ISSUE THREAD

**Issue by divz1010** [naiveHobo/InvoiceNet#4]
Hi,
   Can you please provide the dataset and supported files, it looks interesting I want to run and check.

Thanks in advance

**Comment by divz1010** [comment]
Hi Sarthak,

It will be very helpful if you provide a dataset for this example. I am unable to test/run this script.

**Comment by naiveHobo** [comment]
I added the data set file and some supporting files in the following commit: a931196
Closing this issue.
