### ISSUE TITLE
Cuda 10.0 not supported?

### ISSUE THREAD

**Issue by mirfan899** [naiveHobo/InvoiceNet#49]
I've installed the InvoiceNet.
![invoicenet](https://user-images.githubusercontent.com/3822565/100870244-22f85f80-34c0-11eb-995f-f49c4a14ee49.png)

but when I try to run the trainer it throws the error
```shell
 python trainer.py 
2020-12-02 16:39:44.983352: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib:/usr/local/cuda-10.0/lib64:/usr/local/cuda/extras/CUPTI/lib64
2020-12-02 16:39:44.983372: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```
It seems, it supports only CUDA 10.1 but not CUDA 10.

**Comment by agupta231** [comment]
Did you remember to install the `gpu` version of your DL library? I had a similar issue but it got resolved but uninstalling everything, installing the DL library first. 

iirc I already had my env setup (already installed all of the deps). Then I got rid of the cpu version of tf:

```
pip uninstall tensorflow 
```

And install the gpu version (remember to install the right version!):

```
pip install tensorflow-gpu==2.3.0
```

And that worked for me! Make sure to install the version of TF that fits your cuda version.

**Comment by agupta231** [comment]
I believe that according to [this](https://www.tensorflow.org/install/source#linux), tensorflow 2.3.0 might only be compatible with cuda 10.1.

**Comment by mirfan899** [comment]
Exactly.

**Comment by naiveHobo** [comment]
This is not something I can support out of the box. You need to ensure your CUDA version is compatible with the tensorflow version you're using. You can try downgrading to the last tensorflow 2.0 version compatible with CUDA 10.0 here:
https://github.com/naiveHobo/InvoiceNet/blob/0b0bd634a9ec2eec2c708dcd220da75e4c2a56c0/setup.py#L245
