### ISSUE TITLE
dftrain.pk

### ISSUE THREAD

**Issue by zj9433** [naiveHobo/InvoiceNet#5]
hi, thanks for sharing, it's quite usefully. But could you share a sample training file: dftrain.pk? Would like to see the exact format of it.

**Comment by saifu-rahman** [comment]
Yes, am also eager to get the traiing data "data/train_api.pk". @naiveHobo  Can you please share the link to download it..

**Comment by bhaskar2500** [comment]
As per your previous comments you uploaded the data files inside the data folder . I can only see the word embeddings but unable to see any model file /training data file (train_api.pk) .Could you attache the file repository

**Comment by thanhlam1508** [comment]
@naiveHobo Hi, could you please upload the train_api file since I cannot find any file in the repository?

**Comment by dajor** [comment]
@naiveHobo would be great if you can upload the train_api and some more examples
