### ISSUE TITLE
how much training data required to train model?

### ISSUE THREAD

**Issue by cnithin951** [naiveHobo/InvoiceNet#52]

**Comment by agupta231** [comment]
+1 Additionally, you guys mentioned that you have some sort of data extraction pipeline?

Our team just wants to do a baby test of the net, so we were planning on using a couple of personal invoices to get a basic training going. Do you guys have any recommendations for labeling other than using the GUI?

**Comment by agupta231** [comment]
Found the answer in #17. Basically @naiveHobo's response:
> This is really a question with no good answer. I've seen decent performance for some general fields like total amount and invoice number with as little as 100 samples. But there's no guarantee that a model trained for these fields on a small dataset would be able to generalize well. Other, slightly more complex fields like invoice date take a lot more samples (~500) to produce decent results.
