### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by arpitkumar1412** [naiveHobo/InvoiceNet#54]
Restoring total_amount parser ./models/parsers/amount/best...
Restoring all ./models/invoicenet/total_amount/best...
invoice-template-us-neat-750px.png 0/0

Filename: invoice-template-us-neat-750px.json
Traceback (most recent call last):
  File "predict.py", line 92, in <module>
    main()
  File "predict.py", line 83, in main
    labels[field] = predictions[field][idx]
IndexError: list index out of range

Is this an issue because tesseract wasn't able to read the data? I have attached the image file
![invoice-template-us-neat-750px](https://user-images.githubusercontent.com/44163596/103775884-a9bad200-5054-11eb-990a-42b408bcda28.png)

**Comment by naiveHobo** [comment]
What's the exact command you ran?
