### ISSUE TITLE
I can't prepar and train my dataset

### ISSUE THREAD

**Issue by soufianelb** [naiveHobo/InvoiceNet#55]
error: c:\Users\miniconda3\envs\InvoiceNet\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 774, in next
    raise StopIteration
StopIteration

can anyone help me ?

**Comment by wbtan7** [comment]
Try using more training data, I got similar error when I try with only 1 training data.

**Comment by soufianelb** [comment]
oke, it's working by 2 or more pdf files. I need a large dataset

**Comment by naiveHobo** [comment]
I've added warnings for when the training dataset is not enough to create proper training/validation splits. Closing this issue.
