### ISSUE TITLE
creae_ngrams missing 2 required position arguments

### ISSUE THREAD

**Issue by rvdsarr** [naiveHobo/InvoiceNet#59]
Hi guys, 

Im getting the following error when training a pdf document. Any idea what this might be?
Thanks, Roy
<img width="686" alt="Screenshot_4" src="https://user-images.githubusercontent.com/10889885/105044449-08297c80-5a67-11eb-84c7-ddd29c8910a2.png">

**Comment by mbx2020** [comment]
Hi,
same problem for me.

**Comment by naiveHobo** [comment]
Should be fixed in the latest commit
