### ISSUE TITLE
Architecture of CloudScan

### ISSUE THREAD

**Issue by mmmichl** [naiveHobo/InvoiceNet#6]
Hi,
Thank you for sharing your implementation.

I have a question regarding the CloudScan model. Do you implement the proposed architecture: dense - dense - BI-LSTM - dense - dense?
As far as I understood your code, this is not the case.
If I am right, what is your reason to diverge from the proposed architecture?

Cheers, Michael

**Comment by Atharva13** [comment]
Yeah I also saw the diifference in the architecture.
Also could please share on how to convert the original textual data format into the pickle file.
So that it could be helpful for us to train on our own data
