### ISSUE TITLE
Installation failed on Windows and Ubuntu

### ISSUE THREAD

**Issue by Lyror** [naiveHobo/InvoiceNet#72]
Hello,

i tried to install InvoiceNET on Windows 10 and on WSL2 Ubuntu 20.04 but in both cases I got this error:

> ERROR: Cannot install InvoiceNet and invoicenet==0.1 because these package versions have conflicting dependencies.
>The conflict is caused by:
    invoicenet 0.1 depends on numpy~=1.19.2
    opencv-python 4.5.1.48 depends on numpy>=1.17.3
    tensorflow 2.3.0 depends on numpy<1.19.0 and >=1.16.0
>To fix this you could try to:
>1. loosen the range of package versions you've specified
>2. remove package versions to allow pip attempt to solve the dependency conflict
>ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

How can I fix it?

**Comment by SularuStefan** [comment]
I had the same error, but in my case, I didn't have cuda, so the setup installed the 2.3.0 version of tensorflow. I changed the required version for numpy to 1.18 to dismiss this conflict (in the setup.py file). I was expecting something to go wrong but until now, no problems occured.

**Comment by naiveHobo** [comment]
Should be fixed now. Thank you for pointing out this bug!
