### ISSUE TITLE
Not able to prepare the data for training using extractor GUI.

### ISSUE THREAD

**Issue by shirish100** [naiveHobo/InvoiceNet#82]
Hi, Firstly the work that you have done looks great. But I got into a  technical glitch which I am not able to solve. 

I ve added few custom labels, which gets reflected in the extractor GUI, but I am not able to select those labels for annotating. 

Can you please suggest as what I should do to select and start labelling?

**Comment by shirish100** [comment]
![image](https://user-images.githubusercontent.com/16833805/123249845-04fb5680-d507-11eb-847c-1185b4baca9b.png)
The highlighted checkbox is what I am not able to access.

**Comment by shirish100** [comment]
> Hi, Firstly the work that you have done looks great. But I got into a technical glitch which I am not able to solve.
> 
> I ve added few custom labels, which gets reflected in the extractor GUI, but I am not able to select those labels for annotating.
> 
> Can you please suggest as what I should do to select and start labelling?

The problem is solved by me.

**Comment by dankocrama980** [comment]
@shirish100  can you please explain how did you solve the problem we are facing the same issue

**Comment by indigitale** [comment]
i have the same problem.. anyone can help me? Thanks!

**Comment by rafjerry** [comment]
The field checkboxes become active automatically if InvoiceNet is able to find a trained model for a field
