### ISSUE TITLE
Question : Example of date for training.

### ISSUE THREAD

**Issue by hicka** [naiveHobo/InvoiceNet#85]
In what format should i provide the invoice_date while training?
Say if the invoice displays date as 12-Dec-2019, should i write 12/12/2019 or just as it is in the invoice in the json file?
Im not able to extract invoice date when i train as it is in the invoice & it always extracts the same date for all invoices. Or maybe the dataset is too small (500 invoices) ?

**Comment by hicka** [comment]
I was able to get better results by training more.

**Comment by RamonGO** [comment]
> In what format should i provide the invoice_date while training? Say if the invoice displays date as 12-Dec-2019, should i write 12/12/2019 or just as it is in the invoice in the json file? Im not able to extract invoice date when i train as it is in the invoice & it always extracts the same date for all invoices. Or maybe the dataset is too small (500 invoices) ?

Hi @hicka , how did you do it finally? I´m having the same issue with 2000 invoices training.

Regards,
