### ISSUE TITLE
ImageMagick error

### ISSUE THREAD

**Issue by Dyex719** [naiveHobo/InvoiceNet#9]
You might want to mention this in the docs:

To fix the wand.exceptions.PolicyError: not authorized error:
The user needs to change the policy in /etc/ImageMagick-6/policy.xml for PDFs to read.
i.e: `<policy domain="coder" rights="read" pattern="PDF" />`

**Comment by naiveHobo** [comment]
Yup, great catch. I'd fixed this earlier in my system but didn't document it properly.
